name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Download dependencies
        run: |
          go mod download golang.org/x/sys
          go mod tidy

      - name: Run main.go
        run: go run cmd/painter/main.go
        env:
          CI: true

      - name: Run all tests
        run: go test ./...